### ISSUE TITLE
Hot Reload when changes in SCSS

### ISSUE THREAD

**Issue by haroldao** [younessidbakkasse/shopify-webpack-with-os2-features#3]
(Je sais pas si c'est possible... mais genre reload quand y'a un changement dans le SCSS => reload le 127.0.0.1:9292)

**Comment by younessidbakkasse** [comment]
Oui c'est totalement possible, il suffit de lancer le serveur de développement avec la commande `yarn serve` puis activer le Watch mode de Webpack avec la commande `yarn watch` pour compiler ton code SCSS/JS à chaque fois tu fais des modifications dans le dossier `<theme>/src`. Pour la deuxième commande `yarn watch`, **il faudra une autre fenêtre du Shell**.

**Comment by haroldao** [comment]
yes c'est ce que j'ai fait hier... (et je viens de réessayer... et rien). Je suis obliger de reload la page pour voir les changements.

**Comment by younessidbakkasse** [comment]
That's inusual, it works fine with me **(check this [preview](https://streamable.com/q31jhz))**. Perhaps it due to compilation time, did you try to troubleshoot the issue, did you check the compiled files in the `<theme>/assets` folder.

**Comment by haroldao** [comment]
Ok thanks :). Your lucky 😅... I will check what's going on my side🤗

**Comment by haroldao** [comment]
Toujours le meme problème ... (ma avec ta mAj)

**Comment by younessidbakkasse** [comment]
> Toujours le meme problème ... (ma avec ta mAj)

J'ai pas très bien compris ? (t'as utilisé la dernière version du setup) parceque normalement, quant tu fais tes changement dans le dossier ```src/styles```en **SCSS** , Webpack compile le code dans le dossier ```assets```, du coup Shopify HOTRELOAD detect les changement et rafraîchie la page immédiatement.

Moi ça marche parfait avec Node >= 14.xx

**Comment by haroldao** [comment]
tu penses que j'ai autre chose à MàJ ?

**Comment by haroldao** [comment]
Pour le Hot R. tu utilises 127.XX ou ton url shopify ?

**Comment by younessidbakkasse** [comment]
Est ce que t'as bien vérifie que tu es en watch mode, c'est-à-dire il faut lancer deux session shell, une pour Shopify-cli (affichage en blue) avec la commande ```yarn serve``` ou  ```shopify theme serve```, une autre pour Webpack, (affichage en vert) avec la commande ```yarn watch```

**Comment by haroldao** [comment]
Non j'étais en `npm run start` (c'est la même chose). Je viens de test ce que tu dis et toujours pareil pas de hot reload 😅😭😭

**Comment by haroldao** [comment]
Enfaite le truc, en plus de pas avoir de reload quand je refresh y'a rien qui se passe ... je suis obligé d'attendre une vingtaine de secondes pour avoir les changements (après un refresh)😭😭😭

**Comment by haroldao** [comment]
(Et au passage : c'est pas seulement que pour le SCSS... c'est également la même chose pour les fichiers `.liquid` etc...)

**Comment by younessidbakkasse** [comment]
Ca marche très bien pour moi, et pour des potes aussi, un jour j'ai eu un bug, à cause de Shopify-cli comme le tien... Ah si c'est liquid aussi donc forcement à cause de Shopify cli. il faut redémarrer l'ordi, si ce que j'ai fais un jour.

**Comment by haroldao** [comment]
Ok je vais redémarrer ✅ (btw mon SHOPIFY CLI est à jour)

**Comment by haroldao** [comment]
Bon bah ça marche pas (tant pis !)

**Comment by younessidbakkasse** [comment]
C'est une bug de Shopify CLI, essaye d'ajouter une section sur le customizer, et voir si les modifs apparaitre après le rafraîchissement de la page sinon signale le bug à Shopify ici => https://github.com/Shopify/shopify-cli/issues
