### ISSUE TITLE
Missing "collections" section

### ISSUE THREAD

**Issue by marioloncarek** [younessidbakkasse/shopify-webpack-with-os2-features#9]
list-collections.json requires `collections` section which does not exists so `serve` displays error

**Comment by younessidbakkasse** [comment]
Thanks for your feedback.

**Comment by marioloncarek** [comment]
@younessidbakkasse no problem, thank you for great lib! Let me know if i can help in any way. 

PS this works great

**Comment by younessidbakkasse** [comment]
Your welcome, well I would use some help with ```src/app```, I just drafted a new release with typescript support and I would love to add utility functions that added product to cart and check focus etc...
